import numpy as np
import plotly.graph_objects as go
import streamlit as st

from demo_data.generator import generate_state_timeseries, predicted_next_state, STATE_FEATURES, SCENARIOS
from utils.components import page_header, glass_card_open, glass_card_close, illustrative_tag, quiet_note
from utils.theme import ACCENT_CYAN, RISK_HIGH


def render():
    page_header("DATA LAYER · P3", "Network State",
                "The system aggregates flow-level observations into temporal network states rather than treating every flow independently.")

    scenario = st.selectbox("Scenario", SCENARIOS, index=1, key="ns_scenario")
    df = generate_state_timeseries(scenario, n_windows=24)
    illustrative_tag()

    glass_card_open("STATE TIMELINE")
    labels = [f"T-{len(df)-1-i}" if i < len(df) - 1 else "T (current)" for i in range(len(df))]
    idx = st.select_slider("Select time window", options=list(range(len(df))),
                            format_func=lambda i: labels[i], value=len(df) - 1)
    glass_card_close()

    row = df.iloc[idx]
    is_current = idx == len(df) - 1

    c1, c2 = st.columns([1, 1.3])
    with c1:
        glass_card_open("WINDOW SUMMARY")
        st.markdown(f"**Label:** `{labels[idx]}`")
        st.markdown(f"**Timestamp (illustrative):** window #{idx} · 60s bucket")
        st.markdown(f"**Flows in window (demo):** {int(150 + row['Packet volume']*900)}")
        st.markdown(f"**Packet volume (norm):** {row['Packet volume']:.2f}")
        st.markdown(f"**Byte volume (norm):** {row['Byte volume']:.2f}")
        st.markdown(f"**Active ports (demo):** {int(4 + row['Port diversity']*60)}")
        st.markdown(f"**IAT mean / variance:** {row['IAT mean']:.2f} / {row['IAT variance']:.2f}")
        st.markdown(f"**Bidirectional ratio:** {row['Bidirectional ratio']:.2f}")
        if is_current:
            st.info("This is S_t. Selecting the last window also unlocks the predicted Ŝ(t+1) radar to the right.")
        glass_card_close()

    with c2:
        glass_card_open("STATE VECTOR — RADAR VIEW")
        categories = STATE_FEATURES + [STATE_FEATURES[0]]
        values = list(row[STATE_FEATURES]) + [row[STATE_FEATURES[0]]]

        fig = go.Figure()
        fig.add_trace(go.Scatterpolar(
            r=values, theta=categories, fill="toself", name="S_t",
            line=dict(color=ACCENT_CYAN), fillcolor="rgba(63,208,224,0.15)",
        ))
        if is_current:
            nxt = predicted_next_state(row, scenario)
            nvals = list(nxt[STATE_FEATURES]) + [nxt[STATE_FEATURES[0]]]
            fig.add_trace(go.Scatterpolar(
                r=nvals, theta=categories, fill="toself", name="Ŝ(t+1) (predicted)",
                line=dict(color=RISK_HIGH, dash="dot"), fillcolor="rgba(242,153,74,0.10)",
            ))
        fig.update_layout(
            template="plotly_dark", paper_bgcolor="rgba(0,0,0,0)",
            polar=dict(radialaxis=dict(range=[0, 1], showticklabels=True, gridcolor="#232d45"),
                       bgcolor="rgba(0,0,0,0)"),
            height=380, margin=dict(l=30, r=30, t=20, b=20),
            legend=dict(orientation="h", y=-0.1),
        )
        st.plotly_chart(fig, use_container_width=True)
        glass_card_close()

    glass_card_open("STATE VECTOR — BAR VIEW")
    fig2 = go.Figure(go.Bar(
        x=list(row[STATE_FEATURES]), y=STATE_FEATURES, orientation="h",
        marker_color=ACCENT_CYAN,
    ))
    fig2.update_layout(
        template="plotly_dark", paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        height=300, margin=dict(l=10, r=10, t=10, b=10), xaxis_range=[0, 1],
    )
    st.plotly_chart(fig2, use_container_width=True)
    quiet_note("All window statistics are generated by the demo data engine for illustration.")
    glass_card_close()
