import streamlit as st

from demo_data.generator import generate_state_timeseries, predicted_next_state, STATE_FEATURES, SCENARIOS
from utils.components import page_header, glass_card_open, glass_card_close, illustrative_tag, quiet_note
from utils.theme import ACCENT_CYAN, RISK_SAFE, RISK_HIGH


def render():
    page_header("MODELING LAYER · P4", "LSTM World Model",
                "Learns network-state transition dynamics — it does not classify traffic directly.")

    glass_card_open()
    st.markdown(
        f"""
        <div style="text-align:center; padding: 6px 0 14px 0; font-family:'JetBrains Mono',monospace;
        font-size:15px; color:{ACCENT_CYAN}; border:1px solid #232d45; border-radius:10px; background:#101728;">
        <div style="padding:14px;">"The LSTM never receives the attack/benign label as its direct prediction target."</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    c1, c2 = st.columns(2)
    with c1:
        st.markdown("##### Conventional IDS")
        st.code(
            "Flow 1 → Attack?\nFlow 2 → Attack?\nFlow 3 → Benign?\nFlow 4 → Attack?",
            language="text",
        )
        st.caption("Per-flow, independent, label-supervised classification.")
    with c2:
        st.markdown("##### Our World Model")
        st.code(
            "S(t-k+1)\n   ↓\nS(t-k+2)\n   ↓\n   ...\n   ↓\n  S_t\n   ↓\n  LSTM\n   ↓\nŜ(t+1)\n   ↓\nRisk Derivation\n   ↓\nInfiltration Probability",
            language="text",
        )
        st.caption("Temporal, state-based, self-supervised next-state prediction.")
    glass_card_close()

    glass_card_open("MODEL ARCHITECTURE (PLANNED)")
    st.code(
        "Input sequence [S(t-T+1) ... S_t]\n"
        "        ↓\n"
        "LSTM temporal encoder\n"
        "        ↓\n"
        "Hidden representation h_t\n"
        "        ↓\n"
        "Future-state prediction head\n"
        "        ↓\n"
        "Predicted Ŝ(t+1)",
        language="text",
    )
    st.markdown(
        "**Input:** history of network states ending at S_t &nbsp;·&nbsp; "
        "**Target:** future state vector S_(t+1) &nbsp;·&nbsp; **Not:** attack/benign label"
    )
    glass_card_close()

    glass_card_open("STATE VECTOR EXPLORER")
    illustrative_tag()
    scenario = st.selectbox("Scenario", SCENARIOS, index=1, key="wm_scenario")
    df = generate_state_timeseries(scenario, n_windows=40)
    idx = st.slider("Select window t", 0, len(df) - 1, len(df) - 1, key="wm_window")
    current = df.iloc[idx]
    next_state = predicted_next_state(current, scenario)

    c1, c2 = st.columns(2)
    with c1:
        st.markdown("**S_t (current, illustrative)**")
        rows = "\n".join(f"{f:<22}{current[f]:.2f}" for f in STATE_FEATURES)
        st.code(rows, language="text")
    with c2:
        st.markdown("**Ŝ(t+1) — predicted next state (illustrative)**")
        lines = []
        for f in STATE_FEATURES:
            delta = next_state[f] - current[f]
            arrow = "↑" if delta > 0.01 else ("↓" if delta < -0.01 else "→")
            lines.append(f"{f:<22}{next_state[f]:.2f}  {arrow}")
        st.code("\n".join(lines), language="text")

    quiet_note("Values above are generated by the demo data engine, not a trained model. See DEMO / SIMULATED labels.")
    glass_card_close()
